### ISSUE TITLE
typo: `mechainsm` folder should be named `mechanism`

### ISSUE THREAD

**Issue by plalx** [WaltonChain/WaltonChain_CrossChain#1]
The  `mechainsm` folder should be named `mechanism`.

**Comment by simplest-circuits** [comment]
I think they meant meCHAINsm and not a mechanism like you understand 😉

**Comment by plalx** [comment]
I thought of that too, but it was originally named `mechanism` during the limited community testing process and that's why I've pointed it out.

**Comment by ko12ko** [comment]
It has been fixed.
